theme: jekyll-theme-cayman
repository: glenn2223/vscode-live-sass-compiler

gems:
  - jekyll-seo-tag

title: Live Sass Compiler | VSCode Extension
description : Compile Sass or Scss to CSS at realtime with live browser reload.
author : Glenn Marks
social:
  name: Glenn Marks
  links:
    - https://github.com/glenn2223/vscode-live-sass-compiler
    - https://marketplace.visualstudio.com/items?itemName=glenn2223.live-sass
lang: en_IN

## Uncomment below for local test
# github: [metadata]

